# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qsmq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qsmq.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nqsmq.proto\"2\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\",\n\x07Polygon\x12\x11\n\x01p\x18\x01 \x03(\x0b\x32\x06.Point\x12\x0e\n\x06\x63losed\x18\x02 \x01(\x08\"%\n\nSegmObject\x12\x17\n\x05polys\x18\x01 \x03(\x0b\x32\x08.Polygon\"\x94\x01\n\x10ObjectAnnotation\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x13\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x05.BBox\x12\x19\n\x04segm\x18\x04 \x01(\x0b\x32\x0b.SegmObject\x12\x1d\n\rflorplanpoint\x18\x05 \x01(\x0b\x32\x06.Point\x12\x10\n\x08\x66\x65\x61tures\x18\x06 \x01(\t\"{\n\tImageView\x12\x16\n\x0e\x63onversionType\x18\x01 \x01(\x05\x12\x18\n\x10\x63onversionParams\x18\x02 \x03(\x02\x12,\n\x11objectAnnotations\x18\x03 \x03(\x0b\x32\x11.ObjectAnnotation\x12\x0e\n\x06imgKey\x18\x04 \x01(\t\"T\n\x0b\x43\x61meraImage\x12\x17\n\x0fvideoStreamName\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x19\n\x05views\x18\x03 \x03(\x0b\x32\n.ImageViewb\x06proto3')
)




_BBOX = _descriptor.Descriptor(
  name='BBox',
  full_name='BBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='BBox.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='BBox.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='BBox.w', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='BBox.h', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=64,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='Polygon.p', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closed', full_name='Polygon.closed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=141,
)


_SEGMOBJECT = _descriptor.Descriptor(
  name='SegmObject',
  full_name='SegmObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='polys', full_name='SegmObject.polys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=180,
)


_OBJECTANNOTATION = _descriptor.Descriptor(
  name='ObjectAnnotation',
  full_name='ObjectAnnotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_id', full_name='ObjectAnnotation.class_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='ObjectAnnotation.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bbox', full_name='ObjectAnnotation.bbox', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segm', full_name='ObjectAnnotation.segm', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='florplanpoint', full_name='ObjectAnnotation.florplanpoint', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='ObjectAnnotation.features', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=331,
)


_IMAGEVIEW = _descriptor.Descriptor(
  name='ImageView',
  full_name='ImageView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conversionType', full_name='ImageView.conversionType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conversionParams', full_name='ImageView.conversionParams', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objectAnnotations', full_name='ImageView.objectAnnotations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imgKey', full_name='ImageView.imgKey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=456,
)


_CAMERAIMAGE = _descriptor.Descriptor(
  name='CameraImage',
  full_name='CameraImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoStreamName', full_name='CameraImage.videoStreamName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CameraImage.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='views', full_name='CameraImage.views', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=542,
)

_POLYGON.fields_by_name['p'].message_type = _POINT
_SEGMOBJECT.fields_by_name['polys'].message_type = _POLYGON
_OBJECTANNOTATION.fields_by_name['bbox'].message_type = _BBOX
_OBJECTANNOTATION.fields_by_name['segm'].message_type = _SEGMOBJECT
_OBJECTANNOTATION.fields_by_name['florplanpoint'].message_type = _POINT
_IMAGEVIEW.fields_by_name['objectAnnotations'].message_type = _OBJECTANNOTATION
_CAMERAIMAGE.fields_by_name['views'].message_type = _IMAGEVIEW
DESCRIPTOR.message_types_by_name['BBox'] = _BBOX
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['SegmObject'] = _SEGMOBJECT
DESCRIPTOR.message_types_by_name['ObjectAnnotation'] = _OBJECTANNOTATION
DESCRIPTOR.message_types_by_name['ImageView'] = _IMAGEVIEW
DESCRIPTOR.message_types_by_name['CameraImage'] = _CAMERAIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BBox = _reflection.GeneratedProtocolMessageType('BBox', (_message.Message,), dict(
  DESCRIPTOR = _BBOX,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:BBox)
  ))
_sym_db.RegisterMessage(BBox)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

SegmObject = _reflection.GeneratedProtocolMessageType('SegmObject', (_message.Message,), dict(
  DESCRIPTOR = _SEGMOBJECT,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:SegmObject)
  ))
_sym_db.RegisterMessage(SegmObject)

ObjectAnnotation = _reflection.GeneratedProtocolMessageType('ObjectAnnotation', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTANNOTATION,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:ObjectAnnotation)
  ))
_sym_db.RegisterMessage(ObjectAnnotation)

ImageView = _reflection.GeneratedProtocolMessageType('ImageView', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEVIEW,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:ImageView)
  ))
_sym_db.RegisterMessage(ImageView)

CameraImage = _reflection.GeneratedProtocolMessageType('CameraImage', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAIMAGE,
  __module__ = 'qsmq_pb2'
  # @@protoc_insertion_point(class_scope:CameraImage)
  ))
_sym_db.RegisterMessage(CameraImage)


# @@protoc_insertion_point(module_scope)
